### ISSUE TITLE
Linux package loading

### ISSUE THREAD

**Issue by DWLinden** [kenkellner/jagsUI#1]
It appears that coda is not automatically loaded when using jagsUI in Linux (Ubuntu).

**Comment by kenkellner** [comment]
I've finally nailed down the source of this problem - you must have rjags version >=3-13 or you will run into dependency issues. I've changed the minimum rjags package version in the description file.

**Comment by danlinden** [comment]
Ah, that makes sense.  Pesky dependencies!
