### ISSUE TITLE
Error in saving some of the monitored parameters

### ISSUE THREAD

**Issue by eogmartins** [kenkellner/jagsUI#10]
Hi there,

I keep getting the following error and can't figure how to get around this. It happens after the message "Calculating statistics..."

Error in fill[matrix(ind, 1)] <- input[i] : subscript out of bounds

The error occurs when I ask for some matrices to be monitored (the matrices include some observed values and some NAs to be estimated). I don't get the error if I remove the matrices from the vector of parameters to monitored. I ran the same model using R2jags and didn't get the error so I was wondering if this is an issue with jagsUI...

Thanks,

Eduardo

**Comment by kenkellner** [comment]
Hi Eduardo,

I think this is related to 84b09c7. Would you be willing to send me a minimal example (code + data) that would allow me to reproduce the error? In the meantime, if necessary, I suggest using `jags.basic()` which will still generate the posterior but skip the stats calculation that is causing you issues.

Ken

**Comment by eogmartins** [comment]
Hi Ken,

Thanks very much for your response. Yes, I'll send an example code + 
data to your email.

Cheers,

Eduardo

Ken Kellner wrote:

**Comment by kenkellner** [comment]
This bug appears when trying to determine the dimensions of a parameter (2D or higher) with elements that JAGS does not estimate based on the indexing in the model file. Commit 82194ab appears to fix the issue in the example you provided based on my testing. Can you test the [new version](https://github.com/kenkellner/jagsUI/files/420943/jagsUI_1.4.3.tar.gz) of the package and confirm that you are getting the results you expect?

**Comment by eogmartins** [comment]
Hi Ken,

Thanks very much for fixing this. It's working nicely now and I'm 
getting the results I expect.

Cheers,

Eduardo

**Comment by kenkellner** [comment]
Glad it's working!
