### ISSUE TITLE
Progress bar on parallel

### ISSUE THREAD

**Issue by slozan0** [kenkellner/jagsUI#14]
A progress bar would be very useful when running chains in parallel. I have a very large model (7 Days to run) and having an idea that the process is still running (and not hanged) would be very useful.

**Comment by kenkellner** [comment]
Hi,
Agreed, a progress bar would be useful. However, see my response to issue #6 here for more discussion. I haven't found a good way of printing this information to the console while jagsUI is running in parallel.

**Comment by slozan0** [comment]
Thank you for the quick reply. I apologize for my laziness :)
