### ISSUE TITLE
Graciosly stopping jags from jagsUI

### ISSUE THREAD

**Issue by slozan0** [kenkellner/jagsUI#15]
When running in parallel if R studio is stopped the parallel process remain running in the background. Frankly, I don't know if that is a jagsUI issue.

**Comment by kenkellner** [comment]
This is not something I can control from jagsUI - it's an issue with the dependencies. As far as I understand it is only a Windows issue as well - the child processes are killed properly in Linux (and maybe Mac?). Are you using Windows?

**Comment by slozan0** [comment]
Got it. I been using Windows 10 enterprise and CentOS 6. The child processes have remained running in both OSs after stopping (or killing) the main thread.
