### ISSUE TITLE
A vector with attributes is not a vector

### ISSUE THREAD

**Issue by mikemeredith** [kenkellner/jagsUI#22]
I get a error "Element 'elev' ... cannot be coerced to one of the allowed formats (numeric scalar, vector, matrix, or array)" when `elev` is already a numeric vector but with attributes. I suspect this is because `is.vector` returns `FALSE` for a vector having attributes other than names. This does not apply to `is.matrix` or `is.array`, which happily ignore attributes.

`rjags::jags.model` accepts vectors with attributes. Would be good if `jagsUI` could let them through.

Thanks, Mike

**Comment by kenkellner** [comment]
In d7261042 I made a change to only check `is.numeric` on each data element, so this should be fixed now.
