### ISSUE TITLE
return warnings when verbose = FALSE?

### ISSUE THREAD

**Issue by bstaton1** [kenkellner/jagsUI#26]
This package is great - thanks a ton for putting it together. 

I most commonly use `jags.basic()`, ran in parallel. I generally set the `verbose` argument to `FALSE`, to prevent printing messages telling me JAGS is running in parallel on so many chains, that the inputs were processed properly, and printing the time it took. However, I recently discovered that `verbose = FALSE` also prevents the function from returning warning messages about JAGS reporting insufficient adapting. 

Would you consider separating this behavior, such that users may prevent printing of progress messages, but also be able to see the warnings that are returned? If we don't want warning messages, we can always just wrap this in a `suppressWarnings()` call.

Thanks, and keep up the great work!

**Comment by kenkellner** [comment]
Yes, this is a good idea. I'll make sure the warning shows up in the next version.

**Comment by kenkellner** [comment]
Fixed in 1ade4ccaeac22c0e6e7e67e61f4eede19cdfdb25
