### ISSUE TITLE
traceplot always 'ask's to confirm

### ISSUE THREAD

**Issue by mikemeredith** [kenkellner/jagsUI#27]
The current default for the `ask `argument to `traceplot `is `TRUE`. This means that it asks for page confirmation even if the current device is `pdf`. Sure I could set `ask=FALSE`, but that means I can't just source a script to check it all works without going in and modifying it - and remembering to change back afterwards.

It would be neat if the default were `ask = dev.interactive(orNone = TRUE)`.

That way it would only ask for confirmation if the current device (or the default device if none is open) is the screen.

Thanks, Mike

**Comment by kenkellner** [comment]
Fixed in #28
