### ISSUE TITLE
run_parallel() implementation

### ISSUE THREAD

**Issue by KylieMCurtis** [kenkellner/jagsUI#37]
Hi Ken,

Thanks for being so responsive to my last question about progress status of jags() when parallel processing. I see that there is now a function, run_parallel(), that you have developed however I am confused as to what the parameters are for this function. It has definitely generated a few more questions:

1.) Regarding the inp parameter:
- Should I set     run_parallel(inp = (my jags() model)) ? 
- Do I need the jags() function at all or just      run_parallel(inp = c(data = , inits =, etc..)) ? 

2.) Regarding the quiet parameter
- Is this parameter a True or False choice? 
- If I set it to False will this give me the progress updates? 
- How can I access these updates? I see in the run_parallel code it looks like there is an html written, do I need to set the html location?

Thank you for the help!

- Kylie

**Comment by kenkellner** [comment]
Hi Kylie,

`run_parallel` is an internal function that isn't meant to be used directly. It is called by `jags()` during an analysis in which you have set the option `parallel=TRUE`. 

The recent changes I made were to enable monitoring the progress of MCMC chains while running in parallel in Windows. The solution I previously used for this apparently only works on Linux. The new approach creates a temporary HTML file to which the updates are written, and attempts to open the file in your web browser so you can track progress. 

You don't have to set the HTML location yourself, it's saved to a temporary folder. If for some reason it isn't opened in your browser automatically, the path to the file should be printed to the R console so you can open it yourself. The file should also refresh itself every 10 seconds but you can refresh it manually also to see if there are any new updates.

If you set the option `quiet=TRUE` you will not get any updates, or any other output in your console as the analysis is running.
