### ISSUE TITLE
R-hat values masking traceplot

### ISSUE THREAD

**Issue by ChrKoenig** [kenkellner/jagsUI#43]
Just installed the latest version from Github and plotted some traceplots. Unfortunately, the legend box masks the plots and the legend text is partially outside the plotting area:
<img src="https://user-images.githubusercontent.com/10863705/99526484-9916a580-299b-11eb-89f6-b5f1d0942bd3.png" width=50% height=50%>

Seems like this could be fixed by changing lines 42-43 in `traceplot.R`

    graphics::legend('bottomright', legend=bquote(hat(R) == .(Rhat)),
                   bty='o', bg='white', cex=1.2)

to

    graphics::legend('bottom', legend=bquote(hat(R) == .(Rhat)),
                   bty='n', cex=1.2)

**Comment by kenkellner** [comment]
@mikemeredith can you take a look at this? I can't think of a reason why the legend margins would become so gigantic other than something unusual about the plot device. @ChrKoenig's solution does work but makes the Rhats hard to read if they overlap the traceplot lines. Maybe we need to go back to having them in the title just to be safe.

**Comment by mikemeredith** [comment]
I take it this is RStudio's Plot Zoom? Not sure about the specifics, but I have noticed that manually resizing a plot window with a legend makes a mess and I need to redo the plot. So part of the problem may be with the way `legend` calculates the box size.

Agree that without the white box the value will often be illegible, but not too happy either that a part of the trace plot is obscured. 

So I'd vote for including Rhat in the plot title. Dispensing with "Trace of" will give a bit more space, just the node name and Rhat.

**Comment by kenkellner** [comment]
Fixed in 0d08d0d
