### ISSUE TITLE
parallel processing gone after windows update, very slow

### ISSUE THREAD

**Issue by PhilJoy** [kenkellner/jagsUI#50]
Hi Ken, I've been running jags models with the jagsUI wrapper using the parallel processing to speed things up.  After a windows update courtesy of my employer it is running incredibly slowly.  Looking at the performance tab on the task manager suggests that it's failing to parallel process.  It's even slower than what would happen with sequential chains, but I'm thinking that's the gist of the problem.  Any suggestions?  (Otherwise these models will be running until I retire!)

**Comment by kenkellner** [comment]
Without physical access to the computer this is pretty hard to diagnose. Are you sure you don't have some leftover  processes related to the update that are consuming computing power? `jagsUI` uses the `parallel` package to handle parallel processing, so my suggestion would be to start by running some simple tests with `parallel` to see if that's not working more generally.

Also never hurts to reinstall `jagsUI` and dependencies, along with JAGS itself, after an update just to make sure there isn't some issue there.
